version: "3.7"
services:
  web:
    build: "."
    command: yarn start
    environment:
      DATABASE_URL: "postgres://root:root@database:5432/sample"
      HOST: "127.0.0.1"
    ports:
      - "80:3000"
    volumes:
      - .:/app
